In [ ]:
import numpy as np
# creating arrays
arr = np.array([1,2,3,4,5])
print(arr)

zeros_arr = np.zeros((3,3),dtype=int)
print(zeros_arr)
ones_arr = np.ones((2,2),dtype=int)
print(ones_arr)
arange_arr = np.arange(10)
print(arange_arr)

In [ ]:
zeros_arr = np.zeros((3,3),dtype=int)
print(zeros_arr)
ones_arr = np.ones((2,2),dtype=int)
print(ones_arr)

In [ ]:
arange_arr = np.arange(10)
print(arange_arr)

In [ ]:
#array manipulation
arr = np.array([1,2,3,4,5])
reshaped_arr = np.reshape(5,1)
print(reshaped_arr)

In [ ]:
sliced_arr = arr[2:4]
print(sliced_arr)

In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b =a.T
print(b)

In [ ]:
b=np.split(a,4)
print(b)

In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)

In [ ]:
d=np.linalg.eig(c)
print(d)

In [ ]:
import numpy as np
data = np.loadtxt("/content/drive/MyDrive/dataset/DAP.txt",dtype=int)
d = np.savetxt("/content/dat.txt",data)
print(d)
print(data)

None
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = np.full((2,2),3)
print(a)
print(a.itemsize)

[[3 3]
 [3 3]]
8


In [ ]:
x=[1,2,3]
a = np.asarray(x)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
x = np.array([1,4,0],float)
y = np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


In [ ]:
a=np.array([1,2,3,3,4])
b=np.array([5,6,7,8,8])
print(np.rint(a))
print(np.true_divide(a,b))

[1. 2. 3. 3. 4.]
[0.2        0.33333333 0.42857143 0.375      0.5       ]


In [ ]:
import numpy as np
a=np.array([1,1,2,2,4,4])
b=np.array([1,1,2,2,3,3])
print(np.union1d(a,b))

[1 2 3 4]


In [ ]:
a=np.array([1,1,2,2,4,4])
b=np.array([1,1,2,2,3,3])
print(np.unique(a,b))

In [ ]:
import numpy as np
a=np.array([1,1,2,2,4,4])
b=np.array([1,1,2,2,3,3])
print(np.intersect1d(a,b))

[1 2]


In [ ]:
import numpy as np
a=np.array([1,1,2,2,4,4])
b=np.array([1,1,2,2,3,3])
print(np.setdiff1d(b,a))

[3]


In [ ]:
a=8
b=6
c=np.hypot(a,b)
print(c)

10.0


In [ ]:
x=np.sin(0)
print(x)

0.0


In [ ]:
import numpy as np
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.divmod(a,b))

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.mod(a,b))

[10  0  0  0  0 10]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.divide(a,b))

[ 0.5  1.  15.   2.   2.   2.4]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.multiply(a,b))

[ 200  441   60  800 1250 1500]


In [ ]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
print(np.matmul(a,b))

4251


In [ ]:
from numpy import random
x=random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[-0.47551906  0.76985827  0.12567723]
 [-1.17073296  0.44573564  1.39928661]]


In [ ]:
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[4 8 3 2 7 4 8 7 2 2]


In [ ]:
random.choice([3,5],p=[0.5,0.5],size=(3,5))

array([[3, 3, 3, 5, 3],
       [3, 3, 3, 5, 5],
       [3, 5, 3, 5, 5]])